[project]
name = "Amero-MarketPlace"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.amero-marketplace]
path = "contracts/amero-marketplace.clar"
depends_on = ["sip009-nft-trait", "sip010-ft-trait", "comission-trait"]

[contracts.comission-trait]
path = "contracts/traits/comission-trait.clar"
depends_on = []

[contracts.commission-contract]
path = "contracts/commission-contract.clar"
depends_on = ["comission-trait"]

[contracts.sip009-nft]
path = "contracts/sip009-nft.clar"
depends_on = ["sip009-nft-trait"]

[contracts.sip009-nft-trait]
path = "contracts/traits/sip009-nft-trait.clar"
depends_on = []

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
depends_on = []

[contracts.sip010-token]
path = "contracts/sip010-token.clar"
depends_on = ["sip010-ft-trait"]
